# Generated by Django 6.0.5 on 2026-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('draft', '📝 Черновик'), ('submitted', '📤 Подан'), ('won', '✅ Выигран'), ('lost', '❌ Проигран'), ('cancelled', '⚪ Отменён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Дата и время окончания приёма заявок', null=True, verbose_name='Дедлайн подачи'),
        ),
    ]
