# Generated by Django 6.0.5 on 2026-06-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tender_status_alter_tender_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительная информация по тендеру', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подачи заявок'),
        ),
    ]
