# Generated by Django 6.0.5 on 2026-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tender_comment_alter_tender_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='external_id',
            field=models.CharField(blank=True, help_text='Уникальный номер закупки', max_length=50, null=True, verbose_name='ID на площадке'),
        ),
        migrations.AddField(
            model_name='tender',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL на торговой площадке', null=True, verbose_name='Ссылка на источник'),
        ),
    ]
