# Generated by Django 6.0.5 on 2026-06-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_tender_external_id_tender_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное наименование организации', max_length=200, verbose_name='Наименование')),
                ('inn', models.CharField(help_text='10 цифр для юрлиц, 12 для ИП', max_length=12, unique=True, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, help_text='Основной email организации', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Основной телефон организации', max_length=20, null=True, verbose_name='Телефон')),
                ('contact_person', models.CharField(blank=True, help_text='ФИО контактного лица', max_length=200, null=True, verbose_name='Контактное лицо')),
                ('contact_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность контактного лица')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о клиенте', null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('prospect', '🔍 Потенциальный'), ('active', '✅ Активный'), ('inactive', '⏸️ Неактивный'), ('blacklist', '🚫 В чёрном списке')], default='prospect', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('manager', models.ForeignKey(blank=True, help_text='Пользователь системы, ведущий этого клиента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-updated_at'],
            },
        ),
    ]
