# Generated by Django 6.0.5 on 2026-06-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Привязанный клиент (покупатель)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.client', verbose_name='Клиент'),
        ),
    ]
