# Generated by Django 6.0.5 on 2026-06-07 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_tenderdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('import', 'Импорт'), ('export', 'Экспорт'), ('view', 'Просмотр')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(help_text='Например: Tender, Client', max_length=100, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID изменённого объекта', null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, help_text='Например: Название тендера', max_length=200, verbose_name='Представление объекта')),
                ('changes', models.TextField(blank=True, help_text='JSON с описанием изменений', null=True, verbose_name='Изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='tenders_aud_user_id_896821_idx'), models.Index(fields=['model_name', 'object_id'], name='tenders_aud_model_n_a374a8_idx')],
            },
        ),
    ]
