# Generated by Django 6.0 on 2026-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Название заказчика')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Начальная сумма контракта (₽)')),
                ('deadline', models.DateTimeField(verbose_name='Дата окончания подачи заявок')),
                ('executor_name', models.CharField(max_length=255, verbose_name='ФИО исполнителя')),
                ('procedure_url', models.URLField(verbose_name='Ссылка на процедуру')),
                ('winner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Победитель')),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма заключаемого контракта (₽)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость (₽)')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'ordering': ['-deadline'],
            },
        ),
    ]
