# Generated by Django 6.0.5 on 2026-06-20 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_chatroom_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена прайс')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Ед. измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('approved', 'Согласована'), ('shipped', 'Отгружена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('exported_to_1c', models.BooleanField(default=False, verbose_name='Выгружена в 1С')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выгрузки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_requests', to='tenders.client', verbose_name='Покупатель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
            ],
            options={
                'verbose_name': 'Заявка на отгрузку',
                'verbose_name_plural': 'Заявки на отгрузку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед.')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Скидка от прайса в %', max_digits=5, verbose_name='Скидка, %')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Цена с учётом скидки', max_digits=12, verbose_name='Итоговая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='tenders.product', verbose_name='Продукция')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenders.shipmentrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
            },
        ),
    ]
