# Generated by Django 6.0.5 on 2026-06-20 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0012_product_shipmentrequest_shipmentrequestitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(help_text='До какой даты действует предложение', verbose_name='Срок действия КП')),
                ('payment_terms', models.CharField(help_text='Например: 100% предоплата, 30 дней отсрочка', max_length=200, verbose_name='Условия оплаты')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, help_text='Вводится вручную или через API ТК', max_digits=12, verbose_name='Стоимость доставки')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('total_volume', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Общий объём (м³)')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий вес (кг)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма без доставки')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого с доставкой')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('accepted', 'Принято покупателем'), ('rejected', 'Отклонено'), ('expired', 'Истёк срок действия')], default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='tenders.client', verbose_name='Покупатель')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('shipment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='tenders.shipmentrequest', verbose_name='Заявка на отгрузку')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед.')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка, %')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена с скидкой')),
                ('volume_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Объём 1 шт (м³)')),
                ('weight_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Вес 1 шт (кг)')),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Общий объём (м³)')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий вес (кг)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_items', to='tenders.product', verbose_name='Продукция')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenders.commercialproposal', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'Позиция КП',
                'verbose_name_plural': 'Позиции КП',
            },
        ),
    ]
