# Generated by Django 6.0.6 on 2026-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0013_commercialproposal_commercialproposalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(unique=True, verbose_name='Endpoint')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth Key')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256DH Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Push подписка',
                'verbose_name_plural': 'Push подписки',
            },
        ),
    ]
